### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by guysbrown** [jptaranto/homebridge-roon-outputs#2]
I have tried to install this plugin a few times but get the following error:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/roonlabs/node-roon-api.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-08-27T20_18_50_376Z-debug.log

Command failed. Please review log for details.

**Comment by ascl00** [comment]
It looks like maybe git isn't installed?

**Comment by jptaranto** [comment]
Yes looks like it - the roon node api's are only available on github (they aren't published on npmjs.org for some reason), so you'll need to install git on your homebridge server.
