### ISSUE TITLE
Can't control devices

### ISSUE THREAD

**Issue by Fleskarn** [jptaranto/homebridge-roon-outputs#5]
Hello! On Roon 1.8

Think I have successfully enabled the Extension (it showed up in Roon and I could press Enable). After that lots of speakers appeareded in homekit when I press "add device" but they are not possible to control in any way after adding them? 

"Controls unavailable for this device."

**Comment by jptaranto** [comment]
Yes, unfortunately we can't add any controls via Homebridge at this stage - it's a limitation of the underlying technology.
